#!/usr/bin/env bash
# use awk and bash function to print out from dig
# shellcheck disable=SC2086
dig_out ()
{
    domain=$1
    subdomain=$2
    if [ -n "$domain" ]
    then
	if [ -n "$subdomain" ]
	then
	    display=""
	    uri="$subdomain.$domain"
	    dig "$uri" "A" | awk '/;; ANSWER SECTION:/ { found=1; next} found {
	    	split($1, parts, ".")
	    	printf "The subdomain %s is a %s record and points to %s\n", parts[1], $4, $5 
	        found=0}'
	else
	    display=("www" "lb-01" "web-01" "web-02")
	    uri="$domain"
	    for dom in "${display[@]}"
	    do
		dig "$dom.$uri" "A" | awk '/;; ANSWER SECTION:/ { found=1; next} found {
		    split($1, parts, ".")
		    printf "The subdomain %s is a %s record and points to %s\n", parts[1], $4, $5 
		    found=0}'
	    done
	fi
    fi
}

dig_out "$1" "$2"

exit 0
