#!/usr/bin/env bash

if [ $# -le "3" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path="$1"
	ip="$2"
	user="$3"
	ssh="$4"
	scp -o StrictHostKeyChecking=no -i "$ssh" "$path" "$user@$ip":~/
fi
