#!/usr/bin/env bash
# Configure and debug nginx server to listen on port 80
sudo rm /etc/nginx/sites-enabled/default && ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
