#!/usr/bin/env bash
# Configure and debug nginx server to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill -9 "$(cat /var/run/nginx.pid)"
