#!/usr/bin/env bash
# Configure and debug nginx server to listen on port 80
sudo sed -i "s|listen 8080|listen 80|" "/etc/nginx/sites-enabled/default"
sudo service nginx start
sudo kill -9 "$(cat /var/run/nginx.pid)"
