#!/usr/bin/env bash
# Manage my process

if [ "$1" == "start" ]
then 
	# start daemon process and stored process id in my_process.pid file
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid && echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	id=$(cat /var/run/my_process.pid)
	kill "$id" && rm /var/run/my_process.pid && echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	id=$(cat /var/run/my_process.pid)
	kill "$id" && rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid && echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

