#!/usr/bin/env bash
#Change nginx user from root to nginx and grant necessary priviledges

# add user nginx
sudo useradd nginx > /dev/null 2>&1
sudo passwd -d nginx > /dev/null 2>&1

# Edit configuration file
sudo sed -i '1s|^user .*|user nginx;|' /etc/nginx/nginx.conf
sudo sed -i 's|^\s*listen 80 .*|\tlisten 8080 default_server;|' /etc/nginx/sites-available/default
sudo sed -i 's|^\s*listen \[::\]:80 .*|\tlisten [::]:8080 default_server;|' /etc/nginx/sites-available/default

# grant nginx user necessary least priviledges
chown root:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf

chown root:nginx -R /var/log/nginx/
chmod 755 /var/log/nginx/
chmod 664 /var/log/nginx/*

chown root:nginx -R /var/www/html/
chmod g+r -R /var/www/html/

chown root:nginx -R /etc/nginx/sites-enabled/
chown root:nginx -R /etc/nginx/sites-available/

sudo mkdir -p /run/nginx/
chown nginx:nginx -R /run/nginx/nginx.pid
chmod 770 -R /run/nginx/
sudo sed -i 's|pid /run/nginx.pid;|pid /run/nginx/nginx.pid;|' /etc/nginx/nginx.conf

# Kill any nginx process present
sudo pkill nginx

# restart nginx
sudo service nginx reload > /dev/null 2>&1
sudo -u nginx service nginx restart
