#!/usr/bin/env bash
# Change user from root to nginx and grant necessary priviledges
sudo sed -i '1s|^.?user www-data|user nginx|' /etc/nginx/nginx.conf
sudo sed -i 's|80|8080|' /etc/nginx/sites-available/default
sudo chmod 1777 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
