#!/usr/bin/env bash
#Change nginx user from root to nginx and grant necessary priviledges
sudo sed -i '1s|^user .*|user nginx;|' /etc/nginx/nginx.conf
sudo sed -i 's|^\s*listen 80 .*|\tlisten 8080 default_server;|' /etc/nginx/sites-available/default
sudo chmod 1777 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
